import { ProjectType } from "@/shared/types";

export const projectDB: ProjectType[] = [
  // {
  //   _id: "66544413e27cea13979ac18b",
  //   src: "https://i.ibb.co/svKL0rTD/tsukiwa.webp",
  //   alt: "tsukiwa image",
  //   title: "tsukiwa",
  //   desc: "A place where your “Waifus” matter. This is a website that you can rank, rate, organize and flex your waifus all over the world. This is still currently in designing phase because of my schedule being strict to my academics and gaming. But, I swear that this will be in production once I get free time.",
  //   website: "",
  //   github: "https://github.com/moonbamijam/tsukiwa",
  //   slug: "tsukiwa",
  //   tech: ["nextjs", "typescript", "tailwind"],
  //   tag: ["featured", "in progress", "personal", "web", "open source"],
  // },
  {
    _id: "6654442de27cea13979ac191",
    src: "https://i.ibb.co/CKNHBbqp/realpop.webp",
    alt: "realpop image",
    title: "Realpop",
    desc: "An online store of K-Pop photocards. This is an e-commerce simulation website that is solely dedicated for photocards. This is a school project from my subject called DCIT 26. Realpop is now in production while still maintaining the e-commerce simulation. If you want to know more about Realpop, you can visit the site. If you are thinking of contributing to the project, you can go to its github repository.",
    website: "",
    github: "https://github.com/moonbamijam/realpop-web",
    slug: "realpop",
    tech: ["django", "javascript"],
    tag: ["school", "completed", "web"],
  },
  {
    _id: "66544436e27cea13979ac193",
    src: "https://i.ibb.co/hJTQNHtk/spa.webp",
    alt: "student portal app image",
    title: "Student Portal App",
    desc: "This is another school project from my subject called ITEC 80. It’s an application for students to monitor their academics. This is a team project so I didn’t do all of these by myself, special thanks to my members! If you are by any chance interested in the project, you can visit its github repository.",
    website: "",
    github: "https://github.com/moonbamijam/student-portal-app",
    slug: "student-portal-app",
    tech: ["csharp"],
    tag: ["school", "archived", "application", "completed"],
  },
  {
    _id: "66544444e27cea13979ac197",
    src: "https://i.ibb.co/chPXdvjr/cob-chatbot.webp",
    alt: "cob chatbot image",
    title: "Interactive Chatbot for the City of Bacoor, Cavite",
    desc: "Our capstone project that uses Natural Language Processing (NLP) to deliver smooth experience for the users. The bot is temporarily being hosted by the dummy website we created based on the official website of the Bacoor City Hall.",
    website: "https://www.bacoorchatbot.com/",
    github: "https://github.com/moonbamijam/cob-chatbot",
    slug: "cob-chatbot",
    tech: ["vite", "express", "typescript", "tailwind"],
    tag: ["featured", "open source", "maintaining", "web", "school"],
  },
  {
    _id: "666477446e3e6bb0b63773b7",
    src: "https://i.ibb.co/YBMSWjrq/sassy.webp",
    alt: "sassy css image",
    title: "Sassy CSS",
    desc: "A simple single-page CSS library using Sass!",
    website: "https://sassy-css.vercel.app/",
    github: "https://github.com/moonbamijam/sassy-css",
    slug: "sassy",
    tech: ["vite", "typescript", "sass"],
    tag: ["personal", "open source", "maintaining", "web"],
  },
  {
    _id: "667fb24292501a1327d03a80",
    src: "https://i.ibb.co/RL29CBL/ksa.webp",
    alt: "ksa image",
    title: "Kamote School Admission",
    desc: "A commissioned project from one of my friends that requires a basic CRUD functionality. Me and my friend Ecchiko developed this system that uses PHP as its main tech. If you want to get a copy of this project for yourself, school purposes or whatever. You can contact me to any links I have provided in the contacts page.",
    website: "",
    github: "",
    slug: "ksa",
    tech: ["html", "css", "javascript", "php"],
    tag: ["commission", "web", "for sale", "completed", "Closed Source"],
  },
];
