feature:
- head-branch: 
  - ^feature/*
  - ^feat/*

fix:
- head-branch: ^fix/*

release: 
- head-branch: ^release/*

chore:
- head-branch: 
    - chore/*
    - refactor/*

ui/ux:
- changed-files:
  - any-glob-to-any-file:
    - src/app/**
    - src/assets/**
    - public/**

server: 
- changed-files:
  - any-glob-to-any-file: 
    - src/db/**

devops:
- head-branch: ^release/*
- changed-files:
  - any-glob-to-any-file:
    - .github/**
    - .husky/**
    - .release-it.json

documentation:
- head-branch: docs/*
- changed-files:
  - any-glob-to-any-file: '**/*.md'

dependencies:
- head-branch: deps/*
- changed-files:
  - any-glob-to-any-file: 'pnpm-lock.yaml'