changelog:
  exclude:
    labels:
      - skip-changelog
      - release
    authors:
      - dependabot
  categories:
    - title: BREAKING CHANGES
      labels:
        - breaking-change
    - title: Features
      labels:
        - feature
    - title: Improvements
      labels: 
        - enhancement
    - title: Fixes
      labels:
        - fix
    - title: Others
      labels:
        - chore
        - documentation
        - devops
