overrides:
  minimatch@>=9.0.0 <9.0.6: '>=9.0.6'
  minimatch@>=9.0.0 <9.0.7: '>=9.0.7'
  serialize-javascript@<7.0.5: '>=7.0.5'
  serialize-javascript@<=7.0.2: '>=7.0.3'
  undici@<6.24.0: '>=6.24.0'
  undici@>=6.0.0 <6.24.0: '>=6.24.0'
